# Generated by Django 5.2.4 on 2025-10-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filling_station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Контрагент')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Код')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='BalloonTtn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер ТТН')),
                ('contract', models.CharField(blank=True, max_length=100, verbose_name='Номер договора')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата формирования накладной')),
                ('loading_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_ttn_loading', to='filling_station.balloonsloadingbatch', verbose_name='Партия приёмки')),
                ('unloading_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_ttn_unloading', to='filling_station.balloonsunloadingbatch', verbose_name='Партия отгрузки')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_city', to='ttn.city', verbose_name='Город')),
                ('carrier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_carrier', to='ttn.contractor', verbose_name='Перевозчик')),
                ('consignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_consignee', to='ttn.contractor', verbose_name='Грузополучатель')),
                ('shipper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloons_shipper', to='ttn.contractor', verbose_name='Грузоотправитель')),
            ],
            options={
                'verbose_name': 'Баллоны',
                'verbose_name_plural': 'Баллоны',
                'ordering': ['-id', '-date'],
            },
        ),
    ]
