# Generated by Django 5.2.4 on 2025-10-20 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carousel_number', models.IntegerField(default=1, verbose_name='Номер карусели наполнения')),
                ('is_empty', models.BooleanField(default=False, verbose_name='Принят запрос на наполнение баллона')),
                ('post_number', models.IntegerField(verbose_name='Номер поста наполнения')),
                ('empty_weight', models.FloatField(blank=True, null=True, verbose_name='Вес пустого баллона на посту')),
                ('full_weight', models.FloatField(blank=True, null=True, verbose_name='Вес полного баллона на посту')),
                ('nfc_tag', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер метки')),
                ('serial_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Серийный номер')),
                ('size', models.IntegerField(choices=[(5, 5), (12, 12), (27, 27), (50, 50)], default=50, verbose_name='Объём')),
                ('netto', models.FloatField(blank=True, null=True, verbose_name='Вес пустого баллона')),
                ('brutto', models.FloatField(blank=True, null=True, verbose_name='Вес наполненного баллона')),
                ('filling_status', models.BooleanField(default=False, verbose_name='Готов к наполнению')),
                ('change_at', models.DateTimeField(auto_now=True, verbose_name='Дата и время изменений')),
            ],
            options={
                'verbose_name': 'Карусель',
                'verbose_name_plural': 'Карусель',
                'ordering': ['-change_at'],
            },
        ),
        migrations.CreateModel(
            name='CarouselSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_only', models.BooleanField(default=True, verbose_name='Только чтение с постов наполнения')),
                ('use_weight_management', models.BooleanField(default=False, verbose_name='Использовать коррекцию веса')),
                ('use_common_correction', models.BooleanField(default=False, verbose_name='Использовать общее значение коррекции веса')),
                ('weight_correction_value', models.FloatField(default=0.0, verbose_name='Значение корректировки веса')),
                ('min_balloon_weight', models.FloatField(default=17.8, verbose_name='Минимальный вес баллона')),
                ('max_balloon_weight', models.FloatField(default=46.5, verbose_name='Максимальный вес баллона')),
                ('post_1_correction', models.FloatField(default=0.0, verbose_name='Корректор для 1 поста')),
                ('post_2_correction', models.FloatField(default=0.0, verbose_name='Корректор для 2 поста')),
                ('post_3_correction', models.FloatField(default=0.0, verbose_name='Корректор для 3 поста')),
                ('post_4_correction', models.FloatField(default=0.0, verbose_name='Корректор для 4 поста')),
                ('post_5_correction', models.FloatField(default=0.0, verbose_name='Корректор для 5 поста')),
                ('post_6_correction', models.FloatField(default=0.0, verbose_name='Корректор для 6 поста')),
                ('post_7_correction', models.FloatField(default=0.0, verbose_name='Корректор для 7 поста')),
                ('post_8_correction', models.FloatField(default=0.0, verbose_name='Корректор для 8 поста')),
                ('post_9_correction', models.FloatField(default=0.0, verbose_name='Корректор для 9 поста')),
                ('post_10_correction', models.FloatField(default=0.0, verbose_name='Корректор для 10 поста')),
                ('post_11_correction', models.FloatField(default=0.0, verbose_name='Корректор для 11 поста')),
                ('post_12_correction', models.FloatField(default=0.0, verbose_name='Корректор для 12 поста')),
                ('post_13_correction', models.FloatField(default=0.0, verbose_name='Корректор для 13 поста')),
                ('post_14_correction', models.FloatField(default=0.0, verbose_name='Корректор для 14 поста')),
                ('post_15_correction', models.FloatField(default=0.0, verbose_name='Корректор для 15 поста')),
                ('post_16_correction', models.FloatField(default=0.0, verbose_name='Корректор для 16 поста')),
                ('post_17_correction', models.FloatField(default=0.0, verbose_name='Корректор для 17 поста')),
                ('post_18_correction', models.FloatField(default=0.0, verbose_name='Корректор для 18 поста')),
                ('post_19_correction', models.FloatField(default=0.0, verbose_name='Корректор для 19 поста')),
                ('post_20_correction', models.FloatField(default=0.0, verbose_name='Корректор для 20 поста')),
                ('user', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Настройки карусели',
                'verbose_name_plural': 'Настройки карусели',
            },
        ),
    ]
