# Generated by Django 5.2.4 on 2026-05-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselsettings',
            name='carousel_number',
            field=models.IntegerField(default=1, unique=True, verbose_name='Номер карусели наполнения'),
        ),
    ]
