# Generated by Django 5.2.4 on 2026-09-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0002_balloonsbatch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloonsbatch',
            name='gas_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество принятого газа'),
        ),
        migrations.AlterField(
            model_name='balloonsbatch',
            name='ttn_id',
            field=models.IntegerField(verbose_name='ID ТТН'),
        ),
    ]
