# Generated by Django 5.0.6 on 2024-08-06 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0004_alter_truck_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balloon',
            name='state',
        ),
    ]
