# Generated by Django 5.0.6 on 2024-08-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0005_remove_balloon_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='balloon',
            old_name='full_weight',
            new_name='brutto',
        ),
        migrations.RenameField(
            model_name='balloon',
            old_name='empty_weight',
            new_name='netto',
        ),
    ]
