# Generated by Django 5.0.6 on 2024-08-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0007_rename_capacity_balloon_size_balloon_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changeballoonstatus',
            name='change_status_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата смены статуса'),
        ),
        migrations.AlterField(
            model_name='changeballoonstatus',
            name='change_status_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время смены статуса'),
        ),
    ]
