# Generated by Django 5.0.6 on 2024-08-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0008_alter_changeballoonstatus_change_status_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalloonAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.IntegerField(blank=True, null=True, verbose_name='Номер считывателя')),
                ('amount_of_balloons', models.IntegerField(blank=True, null=True, verbose_name='Количество баллонов по датчику')),
                ('change_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата обновления')),
            ],
        ),
    ]
