# Generated by Django 5.0.6 on 2024-08-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0009_balloonamount'),
    ]

    operations = [
        migrations.AddField(
            model_name='balloonamount',
            name='change_time',
            field=models.TimeField(auto_now_add=True, null=True, verbose_name='Время обновления'),
        ),
        migrations.AlterField(
            model_name='balloonamount',
            name='change_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата обновления'),
        ),
    ]
