# Generated by Django 5.0.6 on 2024-08-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0012_balloon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='balloon',
            name='filling_status',
            field=models.IntegerField(blank=True, null=True, verbose_name='Готов к наполнению'),
        ),
        migrations.AddField(
            model_name='balloon',
            name='update_passport_required',
            field=models.BooleanField(blank=True, null=True, verbose_name='Требуется обновление паспорта'),
        ),
    ]
