# Generated by Django 5.0.6 on 2024-08-19 10:23

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0013_balloon_filling_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RailwayTanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер ж/д цистерны')),
                ('empty_weight', models.IntegerField(blank=True, null=True, verbose_name='Вес пустой цистерны')),
                ('full_weight', models.IntegerField(blank=True, null=True, verbose_name='Вес полной цистерны')),
                ('is_on_station', models.BooleanField(blank=True, null=True, verbose_name='Находится на станции')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='Дата въезда')),
                ('entry_time', models.TimeField(blank=True, null=True, verbose_name='Время въезда')),
                ('departure_date', models.DateField(blank=True, null=True, verbose_name='Дата выезда')),
                ('departure_time', models.TimeField(blank=True, null=True, verbose_name='Время выезда')),
            ],
            options={
                'verbose_name': 'Ж/д цистерна',
                'verbose_name_plural': 'Ж/д цистерны',
            },
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_brand', models.CharField(max_length=20, null=True, verbose_name='Марка прицепа')),
                ('registration_number', models.CharField(max_length=10, verbose_name='Регистрационный знак')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('max_capacity_cylinders_by_type', models.IntegerField(blank=True, null=True, verbose_name='Максимальная вместимость баллонов')),
                ('max_weight_of_transported_cylinders', models.IntegerField(blank=True, null=True, verbose_name='Максимальная масса перевозимых баллонов')),
                ('max_mass_of_transported_gas', models.IntegerField(blank=True, null=True, verbose_name='Максимальная масса перевозимого газа')),
                ('empty_weight', models.IntegerField(blank=True, null=True, verbose_name='Вес пустого т/с')),
                ('full_weight', models.IntegerField(blank=True, null=True, verbose_name='Вес полного т/с')),
                ('is_on_station', models.BooleanField(blank=True, null=True, verbose_name='Находится на станции')),
            ],
            options={
                'verbose_name': 'Прицеп',
                'verbose_name_plural': 'Прицепы',
            },
        ),
        migrations.CreateModel(
            name='TTN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Номер ТТН')),
                ('contract', models.CharField(max_length=20, verbose_name='Номер договора')),
                ('name_of_supplier', models.CharField(max_length=20, verbose_name='Поставщик')),
                ('gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество газа')),
                ('balloons_amount', models.FloatField(blank=True, null=True, verbose_name='Количество баллонов')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата формирования накладной')),
            ],
            options={
                'verbose_name': 'Баллон',
                'verbose_name_plural': 'Баллоны',
            },
        ),
        migrations.AddField(
            model_name='truck',
            name='car_brand',
            field=models.CharField(max_length=20, null=True, verbose_name='Марка авто'),
        ),
        migrations.AddField(
            model_name='truck',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда'),
        ),
        migrations.AddField(
            model_name='truck',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выезда'),
        ),
        migrations.AddField(
            model_name='truck',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата въезда'),
        ),
        migrations.AddField(
            model_name='truck',
            name='entry_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время въезда'),
        ),
        migrations.AddField(
            model_name='truck',
            name='is_on_station',
            field=models.BooleanField(blank=True, null=True, verbose_name='Находится на станции'),
        ),
        migrations.CreateModel(
            name='ShippingBatchRailway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='Дата начала приёмки')),
                ('begin_time', models.TimeField(blank=True, null=True, verbose_name='Время начала приёмки')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания приёмки')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания приёмки')),
                ('gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество принятого газа')),
                ('railway_tanks_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None, verbose_name='Список жд цистерн')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='В работе')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('ttn', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.ttn', verbose_name='ТТН')),
            ],
            options={
                'verbose_name': 'Партия приёмки жд цистерн',
                'verbose_name_plural': 'Партии приёмки жд цистерн',
            },
        ),
        migrations.CreateModel(
            name='ShippingBatchBalloons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='Дата начала приёмки')),
                ('begin_time', models.TimeField(blank=True, null=True, verbose_name='Время начала приёмки')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания приёмки')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания приёмки')),
                ('amount_of_rfid', models.IntegerField(blank=True, null=True, verbose_name='Количество баллонов по rfid')),
                ('amount_of_5_liters', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество 5л баллонов')),
                ('amount_of_20_liters', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество 20л баллонов')),
                ('amount_of_50_liters', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество 50л баллонов')),
                ('gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество принятого газа')),
                ('balloons_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None)),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='В работе')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.truck', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('trailer', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailer', verbose_name='Прицеп')),
                ('ttn', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.ttn', verbose_name='ТТН')),
            ],
            options={
                'verbose_name': 'Партия приёмки баллонов',
                'verbose_name_plural': 'Партии приёмки баллонов',
            },
        ),
        migrations.CreateModel(
            name='ReceivingBatchBalloons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(blank=True, null=True, verbose_name='Дата начала отгрузки')),
                ('begin_time', models.TimeField(blank=True, null=True, verbose_name='Время начала отгрузки')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания отгрузки')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания отгрузки')),
                ('amount_of_rfid', models.IntegerField(blank=True, null=True, verbose_name='Количество баллонов по rfid')),
                ('amount_of_5_liters', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество 5л баллонов')),
                ('amount_of_20_liters', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество 20л баллонов')),
                ('amount_of_50_liters', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество 50л баллонов')),
                ('gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество отгруженного газа')),
                ('balloons_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None)),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='В работе')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.truck', verbose_name='Автомобиль')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('trailer', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailer', verbose_name='Прицеп')),
                ('ttn', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.ttn', verbose_name='ТТН')),
            ],
            options={
                'verbose_name': 'Партия отгрузки баллонов',
                'verbose_name_plural': 'Партии отгрузки баллонов',
            },
        ),
    ]
