# Generated by Django 5.0.6 on 2024-08-20 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0015_alter_shippingbatchballoons_balloons_list'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='railwaytanks',
            name='empty_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес пустой цистерны'),
        ),
        migrations.AlterField(
            model_name='railwaytanks',
            name='full_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес полной цистерны'),
        ),
        migrations.AlterField(
            model_name='receivingbatchballoons',
            name='truck',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.truck', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='receivingbatchballoons',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='shippingbatchballoons',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='empty_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес пустого т/с'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='full_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес полного т/с'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='type',
            field=models.CharField(max_length=50, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='ttn',
            name='balloons_amount',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество баллонов'),
        ),
    ]
