# Generated by Django 5.0.6 on 2024-08-21 05:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0016_alter_railwaytanks_empty_weight_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingBatchBalloons',
            new_name='LoadingBatchBalloons',
        ),
        migrations.RenameModel(
            old_name='ShippingBatchRailway',
            new_name='LoadingBatchRailway',
        ),
        migrations.RenameModel(
            old_name='ReceivingBatchBalloons',
            new_name='UnloadingBatchBalloons',
        ),
    ]
