# Generated by Django 5.0.6 on 2024-08-26 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0017_rename_shippingbatchballoons_loadingbatchballoons_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balloon',
            name='brutto',
        ),
        migrations.RemoveField(
            model_name='balloon',
            name='change_date',
        ),
        migrations.RemoveField(
            model_name='balloon',
            name='change_time',
        ),
        migrations.RemoveField(
            model_name='balloon',
            name='current_examination_date',
        ),
        migrations.RemoveField(
            model_name='balloon',
            name='netto',
        ),
        migrations.RemoveField(
            model_name='balloon',
            name='next_examination_date',
        ),
        migrations.RemoveField(
            model_name='balloon',
            name='status',
        ),
        migrations.RemoveField(
            model_name='balloon',
            name='user',
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Марка прицепа'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='car_brand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Марка авто'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='BalloonHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('netto', models.FloatField(blank=True, null=True, verbose_name='Вес пустого баллона')),
                ('brutto', models.FloatField(blank=True, null=True, verbose_name='Вес наполненного баллона')),
                ('current_examination_date', models.DateField(blank=True, null=True, verbose_name='Дата освидетельствования')),
                ('next_examination_date', models.DateField(blank=True, null=True, verbose_name='Дата следующего освидетельствования')),
                ('status', models.CharField(blank=True, max_length=100, verbose_name='Статус')),
                ('change_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата изменений')),
                ('change_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время изменений')),
                ('balloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='filling_station.balloon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-change_date'],
                'indexes': [models.Index(fields=['-balloon'], name='filling_sta_balloon_5e0e5e_idx')],
            },
        ),
    ]
