# Generated by Django 5.0.6 on 2024-08-26 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0018_remove_balloon_brutto_remove_balloon_change_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balloon',
            options={'ordering': ['-id'], 'verbose_name': 'Баллон', 'verbose_name_plural': 'Баллоны'},
        ),
        migrations.AlterModelOptions(
            name='balloonhistory',
            options={'ordering': ['-change_date'], 'verbose_name': 'История баллона', 'verbose_name_plural': 'История баллонов'},
        ),
        migrations.AlterField(
            model_name='balloonhistory',
            name='balloon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='filling_station.balloon', verbose_name='Метка'),
        ),
        migrations.AddIndex(
            model_name='balloon',
            index=models.Index(fields=['-nfc_tag', '-serial_number'], name='filling_sta_nfc_tag_4ffc6b_idx'),
        ),
    ]
