# Generated by Django 5.0.6 on 2024-08-28 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0021_remove_balloon_insert_insert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unloadingbatchballoons',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.truck', verbose_name='Автомобиль'),
        ),
    ]
