# Generated by Django 5.0.6 on 2024-08-30 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0022_alter_unloadingbatchballoons_truck'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loadingbatchballoons',
            options={'ordering': ['-id'], 'verbose_name': 'Партия приёмки баллонов', 'verbose_name_plural': 'Партии приёмки баллонов'},
        ),
        migrations.AlterModelOptions(
            name='loadingbatchrailway',
            options={'ordering': ['-id'], 'verbose_name': 'Партия приёмки жд цистерн', 'verbose_name_plural': 'Партии приёмки жд цистерн'},
        ),
        migrations.AlterModelOptions(
            name='railwaytanks',
            options={'ordering': ['-id'], 'verbose_name': 'Ж/д цистерна', 'verbose_name_plural': 'Ж/д цистерны'},
        ),
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ['id'], 'verbose_name': 'Прицеп', 'verbose_name_plural': 'Прицепы'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['id'], 'verbose_name': 'Грузовик', 'verbose_name_plural': 'Грузовики'},
        ),
        migrations.AlterModelOptions(
            name='ttn',
            options={'ordering': ['-id'], 'verbose_name': 'Баллон', 'verbose_name_plural': 'Баллоны'},
        ),
        migrations.AlterModelOptions(
            name='unloadingbatchballoons',
            options={'ordering': ['-id'], 'verbose_name': 'Партия отгрузки баллонов', 'verbose_name_plural': 'Партии отгрузки баллонов'},
        ),
        migrations.CreateModel(
            name='LoadingBatchGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата начала приёмки')),
                ('begin_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время начала приёмки')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания приёмки')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания приёмки')),
                ('gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество принятого газа')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='В работе')),
                ('trailer', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailer', verbose_name='Прицеп')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.truck', verbose_name='Автомобиль')),
                ('ttn', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.ttn', verbose_name='ТТН')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Партия приёмки автоцистерн',
                'verbose_name_plural': 'Партии приёмки автоцистерн',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='UnloadingBatchGas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата начала отгрузки')),
                ('begin_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время начала отгрузки')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания отгрузки')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания отгрузки')),
                ('gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество отгруженного газа')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='В работе')),
                ('trailer', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailer', verbose_name='Прицеп')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.truck', verbose_name='Автомобиль')),
                ('ttn', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.ttn', verbose_name='ТТН')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Партия отгрузки автоцистерн',
                'verbose_name_plural': 'Партии отгрузки автоцистерн',
                'ordering': ['-id'],
            },
        ),
    ]
