# Generated by Django 5.0.6 on 2024-09-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0024_rename_loadingbatchgas_gasloadingbatch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='truck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trailer', to='filling_station.truck', verbose_name='Автомобиль'),
            preserve_default=False,
        ),
    ]
