# Generated by Django 5.0.6 on 2024-09-03 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0025_trailer_truck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trailer',
            name='truck',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='trailer', to='filling_station.truck', verbose_name='Автомобиль'),
        ),
    ]
