# Generated by Django 5.0.6 on 2024-09-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0026_alter_trailer_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='departure_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выезда'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время выезда'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='entry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата въезда'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='entry_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время въезда'),
        ),
    ]
