# Generated by Django 5.0.6 on 2024-09-04 07:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0027_trailer_departure_date_trailer_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloonsunloadingbatch',
            name='balloons_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
