# Generated by Django 5.0.6 on 2024-09-09 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0029_rename_railwaytanks_railwaytank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloon',
            name='filling_status',
            field=models.BooleanField(blank=True, null=True, verbose_name='Готов к наполнению'),
        ),
    ]
