# Generated by Django 5.0.6 on 2024-09-15 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0030_alter_balloon_filling_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasloadingbatch',
            name='weight_gas_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество принятого газа (весовая)'),
        ),
        migrations.AddField(
            model_name='gasunloadingbatch',
            name='weight_gas_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество отгруженного газа (весовая)'),
        ),
    ]
