# Generated by Django 5.0.6 on 2024-09-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0031_gasloadingbatch_weight_gas_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ttn',
            options={'ordering': ['-id'], 'verbose_name': 'ТТН', 'verbose_name_plural': 'ТТН'},
        ),
        migrations.AddField(
            model_name='balloonamount',
            name='amount_of_rfid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество баллонов по считывателю'),
        ),
        migrations.AddField(
            model_name='balloonamount',
            name='reader_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='railwaytank',
            name='gas_amount',
            field=models.FloatField(blank=True, null=True, verbose_name='Количество газа'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='max_capacity_cylinders_by_type',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальная вместимость баллонов'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='max_mass_of_transported_gas',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальная масса перевозимого газа'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='max_weight_of_transported_cylinders',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальная масса перевозимых баллонов'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='empty_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес пустого т/с'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='full_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес полного т/с'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='max_capacity_cylinders_by_type',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальная вместимость баллонов'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='max_mass_of_transported_gas',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальная масса перевозимого газа'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='max_weight_of_transported_cylinders',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальная масса перевозимых баллонов'),
        ),
    ]
