# Generated by Django 5.0.6 on 2024-09-17 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0032_alter_ttn_options_balloonamount_amount_of_rfid_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balloon',
            options={'ordering': ['-change_date', '-change_time'], 'verbose_name': 'Баллон', 'verbose_name_plural': 'Баллоны'},
        ),
        migrations.AlterField(
            model_name='trailer',
            name='max_capacity_cylinders_by_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальная вместимость баллонов'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='max_capacity_cylinders_by_type',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальная вместимость баллонов'),
        ),
    ]
