# Generated by Django 5.0.6 on 2024-09-22 12:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0033_alter_balloon_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasunloadingbatch',
            name='trailer',
        ),
        migrations.RemoveField(
            model_name='gasunloadingbatch',
            name='truck',
        ),
        migrations.RemoveField(
            model_name='gasunloadingbatch',
            name='ttn',
        ),
        migrations.RemoveField(
            model_name='gasunloadingbatch',
            name='user',
        ),
        migrations.RemoveField(
            model_name='railwayloadingbatch',
            name='ttn',
        ),
        migrations.RemoveField(
            model_name='railwayloadingbatch',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='balloonsloadingbatch',
            options={'ordering': ['-begin_date', '-begin_time'], 'verbose_name': 'Партия приёмки баллонов', 'verbose_name_plural': 'Партии приёмки баллонов'},
        ),
        migrations.AlterModelOptions(
            name='balloonsunloadingbatch',
            options={'ordering': ['-begin_date', '-begin_time'], 'verbose_name': 'Партия отгрузки баллонов', 'verbose_name_plural': 'Партии отгрузки баллонов'},
        ),
        migrations.AlterModelOptions(
            name='railwaytank',
            options={'ordering': ['-entry_date', '-entry_time'], 'verbose_name': 'Ж/д цистерна', 'verbose_name_plural': 'Ж/д цистерны'},
        ),
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ['-entry_date', '-entry_time'], 'verbose_name': 'Прицеп', 'verbose_name_plural': 'Прицепы'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['-entry_date', '-entry_time'], 'verbose_name': 'Грузовик', 'verbose_name_plural': 'Грузовики'},
        ),
        migrations.AlterModelOptions(
            name='ttn',
            options={'ordering': ['-date'], 'verbose_name': 'ТТН', 'verbose_name_plural': 'ТТН'},
        ),
        migrations.RenameField(
            model_name='trailer',
            old_name='max_capacity_cylinders_by_type',
            new_name='capacity_cylinders',
        ),
        migrations.RenameField(
            model_name='truck',
            old_name='max_capacity_cylinders_by_type',
            new_name='capacity_cylinders',
        ),
        migrations.RemoveField(
            model_name='balloonsloadingbatch',
            name='amount_of_20_liters',
        ),
        migrations.RemoveField(
            model_name='balloonsloadingbatch',
            name='balloons_list',
        ),
        migrations.RemoveField(
            model_name='balloonsunloadingbatch',
            name='amount_of_20_liters',
        ),
        migrations.RemoveField(
            model_name='balloonsunloadingbatch',
            name='balloons_list',
        ),
        migrations.RemoveField(
            model_name='railwaytank',
            name='gas_amount',
        ),
        migrations.RemoveField(
            model_name='ttn',
            name='name_of_supplier',
        ),
        migrations.AddField(
            model_name='balloonsloadingbatch',
            name='amount_of_27_liters',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество 27л баллонов'),
        ),
        migrations.AddField(
            model_name='balloonsloadingbatch',
            name='balloon_list',
            field=models.ManyToManyField(blank=True, to='filling_station.balloon', verbose_name='Список баллонов'),
        ),
        migrations.AddField(
            model_name='balloonsunloadingbatch',
            name='amount_of_27_liters',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество 27л баллонов'),
        ),
        migrations.AddField(
            model_name='balloonsunloadingbatch',
            name='balloon_list',
            field=models.ManyToManyField(blank=True, to='filling_station.balloon', verbose_name='Список баллонов'),
        ),
        migrations.AddField(
            model_name='railwaytank',
            name='gas_type',
            field=models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа'),
        ),
        migrations.AddField(
            model_name='railwaytank',
            name='gas_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Масса перевозимого газа'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='gas_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальный объём перевозимого газа'),
        ),
        migrations.AddField(
            model_name='truck',
            name='max_gas_volume',
            field=models.FloatField(blank=True, null=True, verbose_name='Максимальный объём перевозимого газа'),
        ),
        migrations.AddField(
            model_name='ttn',
            name='consignee',
            field=models.CharField(default='Нет данных', max_length=20, verbose_name='Грузополучатель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ttn',
            name='gas_type',
            field=models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа'),
        ),
        migrations.AddField(
            model_name='ttn',
            name='shipper',
            field=models.CharField(default='Нет данных', max_length=20, verbose_name='Грузоотправитель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trailer',
            name='empty_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес пустого т/с (по техпаспорту)'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='full_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес полного т/с (по техпаспорту)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='empty_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес пустого т/с (по техпаспорту)'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='full_weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Вес полного т/с (по техпаспорту)'),
        ),
        migrations.CreateModel(
            name='AutoGasBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_type', models.CharField(choices=[('l', 'Приёмка'), ('u', 'Отгрузка')], default='Не выбран', max_length=10, verbose_name='Тип партии')),
                ('begin_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата начала приёмки')),
                ('begin_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время начала приёмки')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания приёмки')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания приёмки')),
                ('gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество газа (массомер)')),
                ('gas_type', models.CharField(choices=[('Не выбран', 'Не выбран'), ('СПБТ', 'СПБТ'), ('ПБА', 'ПБА')], default='Не выбран', max_length=10, verbose_name='Тип газа')),
                ('scale_empty_weight', models.FloatField(blank=True, null=True, verbose_name='Вес пустого т/с (весы)')),
                ('scale_full_weight', models.FloatField(blank=True, null=True, verbose_name='Вес полного т/с (весы)')),
                ('weight_gas_amount', models.FloatField(blank=True, null=True, verbose_name='Количество газа (весы)')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='В работе')),
                ('trailer', models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailer', verbose_name='Прицеп')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.truck', verbose_name='Автомобиль')),
                ('ttn', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.ttn', verbose_name='ТТН')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Автоколонка',
                'verbose_name_plural': 'Автоколонка',
                'ordering': ['-begin_date', '-begin_time'],
            },
        ),
        migrations.CreateModel(
            name='RailwayBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата начала приёмки')),
                ('begin_time', models.TimeField(auto_now_add=True, null=True, verbose_name='Время начала приёмки')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания приёмки')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Время окончания приёмки')),
                ('gas_amount_spbt', models.FloatField(blank=True, null=True, verbose_name='Количество принятого СПБТ газа')),
                ('gas_amount_pba', models.FloatField(blank=True, null=True, verbose_name='Количество принятого ПБА газа')),
                ('is_active', models.BooleanField(blank=True, null=True, verbose_name='В работе')),
                ('railway_tank_list', models.ManyToManyField(blank=True, to='filling_station.railwaytank', verbose_name='Список жд цистерн')),
                ('ttn', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.ttn', verbose_name='ТТН')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Партия приёмки жд цистерн',
                'verbose_name_plural': 'Партии приёмки жд цистерн',
                'ordering': ['-begin_date', '-begin_time'],
            },
        ),
        migrations.DeleteModel(
            name='GasLoadingBatch',
        ),
        migrations.DeleteModel(
            name='GasUnloadingBatch',
        ),
        migrations.DeleteModel(
            name='RailwayLoadingBatch',
        ),
    ]
