# Generated by Django 5.0.6 on 2024-09-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0035_alter_autogasbatch_batch_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='railwaytank',
            old_name='number',
            new_name='registration_number',
        ),
        migrations.RenameField(
            model_name='trailer',
            old_name='gas_volume',
            new_name='max_gas_volume',
        ),
    ]
