# Generated by Django 5.0.6 on 2024-10-22 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0037_balloonsloadingbatch_amount_of_12_liters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BalloonSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.IntegerField(default=50, verbose_name='Объём')),
            ],
            options={
                'verbose_name': 'Объём баллона',
                'verbose_name_plural': 'Объём баллона',
            },
        ),
    ]
