# Generated by Django 5.0.6 on 2024-10-22 07:29

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0038_balloonsize'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='balloon',
            name='insert_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='balloon',
            name='update_update',
        ),
        migrations.RemoveField(
            model_name='balloonevent',
            name='size',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='balloon',
            trigger=pgtrigger.compiler.Trigger(name='insert_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "filling_station_balloonevent" ("brutto", "creation_date", "current_examination_date", "id", "manufacturer", "netto", "next_examination_date", "nfc_tag", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "serial_number", "status", "user_id", "wall_thickness") VALUES (NEW."brutto", NEW."creation_date", NEW."current_examination_date", NEW."id", NEW."manufacturer", NEW."netto", NEW."next_examination_date", NEW."nfc_tag", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."serial_number", NEW."status", NEW."user_id", NEW."wall_thickness"); RETURN NULL;', hash='dc1b34bcae500a8c11fd8677e967d2a6f7443f9f', operation='INSERT', pgid='pgtrigger_insert_insert_703b2', table='filling_station_balloon', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='balloon',
            trigger=pgtrigger.compiler.Trigger(name='update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD."brutto" IS DISTINCT FROM (NEW."brutto") OR OLD."creation_date" IS DISTINCT FROM (NEW."creation_date") OR OLD."current_examination_date" IS DISTINCT FROM (NEW."current_examination_date") OR OLD."id" IS DISTINCT FROM (NEW."id") OR OLD."manufacturer" IS DISTINCT FROM (NEW."manufacturer") OR OLD."netto" IS DISTINCT FROM (NEW."netto") OR OLD."next_examination_date" IS DISTINCT FROM (NEW."next_examination_date") OR OLD."nfc_tag" IS DISTINCT FROM (NEW."nfc_tag") OR OLD."serial_number" IS DISTINCT FROM (NEW."serial_number") OR OLD."status" IS DISTINCT FROM (NEW."status") OR OLD."user_id" IS DISTINCT FROM (NEW."user_id") OR OLD."wall_thickness" IS DISTINCT FROM (NEW."wall_thickness"))', func='INSERT INTO "filling_station_balloonevent" ("brutto", "creation_date", "current_examination_date", "id", "manufacturer", "netto", "next_examination_date", "nfc_tag", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "serial_number", "status", "user_id", "wall_thickness") VALUES (NEW."brutto", NEW."creation_date", NEW."current_examination_date", NEW."id", NEW."manufacturer", NEW."netto", NEW."next_examination_date", NEW."nfc_tag", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."serial_number", NEW."status", NEW."user_id", NEW."wall_thickness"); RETURN NULL;', hash='04f76b599850820dfb30a4ae2fd5395bd5db1a62', operation='UPDATE', pgid='pgtrigger_update_update_08342', table='filling_station_balloon', when='AFTER')),
        ),
    ]
