# Generated by Django 5.0.6 on 2024-10-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0039_remove_balloon_insert_insert_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BalloonSize',
        ),
        migrations.AlterField(
            model_name='balloon',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объём'),
        ),
    ]
