# Generated by Django 5.0.6 on 2024-10-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0040_delete_balloonsize_alter_balloon_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balloon',
            name='size',
            field=models.IntegerField(choices=[(5, 5), (12, 12), (27, 27), (50, 50)], default=50, verbose_name='Объём'),
        ),
    ]
