# Generated by Django 5.0.6 on 2024-10-22 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0044_trailertype_truck_new_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='new_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='filling_station.trailertype', verbose_name='Тип'),
        ),
    ]
