# Generated by Django 5.0.6 on 2024-11-02 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0047_rename_new_type_trailer_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='railwaybatch',
            name='ttn',
        ),
        migrations.AddField(
            model_name='railwaybatch',
            name='export_ttn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='export_ttn', to='filling_station.ttn', verbose_name='Возвратная ТТН'),
        ),
        migrations.AddField(
            model_name='railwaybatch',
            name='import_ttn',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='import_ttn', to='filling_station.ttn', verbose_name='ТТН на приёмку'),
        ),
        migrations.AddField(
            model_name='railwaytank',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
