# Generated by Django 5.1.2 on 2024-12-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0048_filepath_remove_railwaybatch_ttn_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='railwaytank',
            options={'ordering': ['-id', '-entry_date', '-entry_time', '-departure_date', '-departure_time'], 'verbose_name': 'Ж/д цистерна', 'verbose_name_plural': 'Ж/д цистерны'},
        ),
        migrations.AlterModelOptions(
            name='trailer',
            options={'ordering': ['-entry_date', '-entry_time', '-departure_date', '-departure_time'], 'verbose_name': 'Прицеп', 'verbose_name_plural': 'Прицепы'},
        ),
        migrations.AlterModelOptions(
            name='truck',
            options={'ordering': ['-entry_date', '-entry_time', '-departure_date', '-departure_time'], 'verbose_name': 'Грузовик', 'verbose_name_plural': 'Грузовики'},
        ),
        migrations.AlterField(
            model_name='ttn',
            name='consignee',
            field=models.CharField(max_length=100, verbose_name='Грузополучатель'),
        ),
        migrations.AlterField(
            model_name='ttn',
            name='contract',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер договора'),
        ),
        migrations.AlterField(
            model_name='ttn',
            name='number',
            field=models.CharField(max_length=100, verbose_name='Номер ТТН'),
        ),
        migrations.AlterField(
            model_name='ttn',
            name='shipper',
            field=models.CharField(max_length=100, verbose_name='Грузоотправитель'),
        ),
    ]
