# Generated by Django 5.1.4 on 2025-02-06 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0049_alter_railwaytank_options_alter_trailer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='railwaybatch',
            options={'ordering': ['-begin_date'], 'verbose_name': 'Партия приёмки жд цистерн', 'verbose_name_plural': 'Партии приёмки жд цистерн'},
        ),
        migrations.AlterModelOptions(
            name='railwaytank',
            options={'ordering': ['is_on_station', '-entry_date', '-entry_time', '-departure_date', '-departure_time'], 'verbose_name': 'Ж/д цистерна', 'verbose_name_plural': 'Ж/д цистерны'},
        ),
        migrations.RemoveField(
            model_name='railwaybatch',
            name='begin_time',
        ),
        migrations.RemoveField(
            model_name='railwaybatch',
            name='end_time',
        ),
        migrations.AlterField(
            model_name='railwaybatch',
            name='begin_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата начала приёмки'),
        ),
        migrations.AlterField(
            model_name='railwaybatch',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания приёмки'),
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер считывателя')),
                ('nfc_tag', models.CharField(blank=True, max_length=30, null=True, verbose_name='Номер метки')),
                ('serial_number', models.CharField(blank=True, max_length=30, null=True, verbose_name='Серийный номер')),
                ('size', models.IntegerField(choices=[(5, 5), (12, 12), (27, 27), (50, 50)], default=50, verbose_name='Объём')),
                ('netto', models.FloatField(blank=True, null=True, verbose_name='Вес пустого баллона')),
                ('brutto', models.FloatField(blank=True, null=True, verbose_name='Вес наполненного баллона')),
                ('filling_status', models.BooleanField(blank=True, null=True, verbose_name='Готов к наполнению')),
                ('change_date', models.DateField(auto_now=True, verbose_name='Дата изменений')),
                ('change_time', models.TimeField(auto_now=True, verbose_name='Время изменений')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Считыватель',
                'verbose_name_plural': 'Считыватели',
                'ordering': ['-change_date', '-change_time'],
            },
        ),
    ]
