# Generated by Django 5.1.4 on 2025-02-09 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filling_station', '0050_alter_railwaybatch_options_alter_railwaytank_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='railwaytank',
            options={'ordering': ['-is_on_station', '-entry_date', '-entry_time', '-departure_date', '-departure_time'], 'verbose_name': 'Ж/д цистерна', 'verbose_name_plural': 'Ж/д цистерны'},
        ),
        migrations.AddField(
            model_name='ttn',
            name='carrier',
            field=models.CharField(default='-', max_length=100, verbose_name='Перевозчик'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='railwaytank',
            name='registration_number',
            field=models.CharField(max_length=20, verbose_name='Номер ж/д цистерны'),
        ),
    ]
